//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3u2-hudson-jaxb-ri-2.2.3-4- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 08:23:55 PM MEZ 
//


package com.eqdkplus.jdkp.rest.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}eqdkp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eqdkp"
})
@XmlRootElement(name = "config")
public class Config {

    protected Eqdkp eqdkp;

    /**
     * Gets the value of the eqdkp property.
     * 
     * @return
     *     possible object is
     *     {@link Eqdkp }
     *     
     */
    public Eqdkp getEqdkp() {
        return eqdkp;
    }

    /**
     * Sets the value of the eqdkp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eqdkp }
     *     
     */
    public void setEqdkp(Eqdkp value) {
        this.eqdkp = value;
    }

}
