//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3u2-hudson-jaxb-ri-2.2.3-4- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 11:58:36 AM MESZ 
//


package com.eqdkplus.jdkp.parse.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}guild"/>
 *         &lt;element ref="{}dkp_name"/>
 *         &lt;element ref="{}version"/>
 *         &lt;element ref="{}layout"/>
 *         &lt;element ref="{}base_layout"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "guild",
    "dkpName",
    "version",
    "layout",
    "baseLayout"
})
@XmlRootElement(name = "eqdkp")
public class Eqdkp {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String guild;
    @XmlElement(name = "dkp_name", required = true)
    protected String dkpName;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String layout;
    @XmlElement(name = "base_layout", required = true)
    protected String baseLayout;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the guild property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuild() {
        return guild;
    }

    /**
     * Sets the value of the guild property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuild(String value) {
        this.guild = value;
    }

    /**
     * Gets the value of the dkpName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDkpName() {
        return dkpName;
    }

    /**
     * Sets the value of the dkpName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDkpName(String value) {
        this.dkpName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayout(String value) {
        this.layout = value;
    }

    /**
     * Gets the value of the baseLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseLayout() {
        return baseLayout;
    }

    /**
     * Sets the value of the baseLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseLayout(String value) {
        this.baseLayout = value;
    }

}
