//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3u2-hudson-jaxb-ri-2.2.3-4- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 11:58:36 AM MESZ 
//


package com.eqdkplus.jdkp.parse.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}multidkp_id"/>
 *         &lt;element ref="{}points_current"/>
 *         &lt;element ref="{}points_current_with_twink"/>
 *         &lt;element ref="{}points_earned"/>
 *         &lt;element ref="{}points_earned_with_twink"/>
 *         &lt;element ref="{}points_spent"/>
 *         &lt;element ref="{}points_spent_with_twink"/>
 *         &lt;element ref="{}points_adjustment"/>
 *         &lt;element ref="{}points_adjustment_with_twink"/>
 *         &lt;element ref="{}points_current_html" minOccurs="0"/>
 *         &lt;element ref="{}points_current_with_twink_html" minOccurs="0"/>
 *         &lt;element ref="{}points_earned_html" minOccurs="0"/>
 *         &lt;element ref="{}points_earned_with_twink_html" minOccurs="0"/>
 *         &lt;element ref="{}points_spent_html" minOccurs="0"/>
 *         &lt;element ref="{}points_spent_with_twink_html" minOccurs="0"/>
 *         &lt;element ref="{}points_adjustment_html" minOccurs="0"/>
 *         &lt;element ref="{}points_adjustment_with_twink_html" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "multidkpId",
    "pointsCurrent",
    "pointsCurrentWithTwink",
    "pointsEarned",
    "pointsEarnedWithTwink",
    "pointsSpent",
    "pointsSpentWithTwink",
    "pointsAdjustment",
    "pointsAdjustmentWithTwink",
    "pointsCurrentHtml",
    "pointsCurrentWithTwinkHtml",
    "pointsEarnedHtml",
    "pointsEarnedWithTwinkHtml",
    "pointsSpentHtml",
    "pointsSpentWithTwinkHtml",
    "pointsAdjustmentHtml",
    "pointsAdjustmentWithTwinkHtml"
})
@XmlRootElement(name = "multidkp_points")
public class MultidkpPoints {

    @XmlElement(name = "multidkp_id")
    protected int multidkpId;
    @XmlElement(name = "points_current")
    protected double pointsCurrent;
    @XmlElement(name = "points_current_with_twink")
    protected double pointsCurrentWithTwink;
    @XmlElement(name = "points_earned")
    protected double pointsEarned;
    @XmlElement(name = "points_earned_with_twink")
    protected double pointsEarnedWithTwink;
    @XmlElement(name = "points_spent")
    protected double pointsSpent;
    @XmlElement(name = "points_spent_with_twink")
    protected double pointsSpentWithTwink;
    @XmlElement(name = "points_adjustment")
    protected double pointsAdjustment;
    @XmlElement(name = "points_adjustment_with_twink")
    protected double pointsAdjustmentWithTwink;
    @XmlElement(name = "points_current_html")
    protected String pointsCurrentHtml;
    @XmlElement(name = "points_current_with_twink_html")
    protected String pointsCurrentWithTwinkHtml;
    @XmlElement(name = "points_earned_html")
    protected String pointsEarnedHtml;
    @XmlElement(name = "points_earned_with_twink_html")
    protected String pointsEarnedWithTwinkHtml;
    @XmlElement(name = "points_spent_html")
    protected String pointsSpentHtml;
    @XmlElement(name = "points_spent_with_twink_html")
    protected String pointsSpentWithTwinkHtml;
    @XmlElement(name = "points_adjustment_html")
    protected String pointsAdjustmentHtml;
    @XmlElement(name = "points_adjustment_with_twink_html")
    protected String pointsAdjustmentWithTwinkHtml;

    /**
     * Gets the value of the multidkpId property.
     * 
     */
    public int getMultidkpId() {
        return multidkpId;
    }

    /**
     * Sets the value of the multidkpId property.
     * 
     */
    public void setMultidkpId(int value) {
        this.multidkpId = value;
    }

    /**
     * Gets the value of the pointsCurrent property.
     * 
     */
    public double getPointsCurrent() {
        return pointsCurrent;
    }

    /**
     * Sets the value of the pointsCurrent property.
     * 
     */
    public void setPointsCurrent(double value) {
        this.pointsCurrent = value;
    }

    /**
     * Gets the value of the pointsCurrentWithTwink property.
     * 
     */
    public double getPointsCurrentWithTwink() {
        return pointsCurrentWithTwink;
    }

    /**
     * Sets the value of the pointsCurrentWithTwink property.
     * 
     */
    public void setPointsCurrentWithTwink(double value) {
        this.pointsCurrentWithTwink = value;
    }

    /**
     * Gets the value of the pointsEarned property.
     * 
     */
    public double getPointsEarned() {
        return pointsEarned;
    }

    /**
     * Sets the value of the pointsEarned property.
     * 
     */
    public void setPointsEarned(double value) {
        this.pointsEarned = value;
    }

    /**
     * Gets the value of the pointsEarnedWithTwink property.
     * 
     */
    public double getPointsEarnedWithTwink() {
        return pointsEarnedWithTwink;
    }

    /**
     * Sets the value of the pointsEarnedWithTwink property.
     * 
     */
    public void setPointsEarnedWithTwink(double value) {
        this.pointsEarnedWithTwink = value;
    }

    /**
     * Gets the value of the pointsSpent property.
     * 
     */
    public double getPointsSpent() {
        return pointsSpent;
    }

    /**
     * Sets the value of the pointsSpent property.
     * 
     */
    public void setPointsSpent(double value) {
        this.pointsSpent = value;
    }

    /**
     * Gets the value of the pointsSpentWithTwink property.
     * 
     */
    public double getPointsSpentWithTwink() {
        return pointsSpentWithTwink;
    }

    /**
     * Sets the value of the pointsSpentWithTwink property.
     * 
     */
    public void setPointsSpentWithTwink(double value) {
        this.pointsSpentWithTwink = value;
    }

    /**
     * Gets the value of the pointsAdjustment property.
     * 
     */
    public double getPointsAdjustment() {
        return pointsAdjustment;
    }

    /**
     * Sets the value of the pointsAdjustment property.
     * 
     */
    public void setPointsAdjustment(double value) {
        this.pointsAdjustment = value;
    }

    /**
     * Gets the value of the pointsAdjustmentWithTwink property.
     * 
     */
    public double getPointsAdjustmentWithTwink() {
        return pointsAdjustmentWithTwink;
    }

    /**
     * Sets the value of the pointsAdjustmentWithTwink property.
     * 
     */
    public void setPointsAdjustmentWithTwink(double value) {
        this.pointsAdjustmentWithTwink = value;
    }

    /**
     * Gets the value of the pointsCurrentHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsCurrentHtml() {
        return pointsCurrentHtml;
    }

    /**
     * Sets the value of the pointsCurrentHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsCurrentHtml(String value) {
        this.pointsCurrentHtml = value;
    }

    /**
     * Gets the value of the pointsCurrentWithTwinkHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsCurrentWithTwinkHtml() {
        return pointsCurrentWithTwinkHtml;
    }

    /**
     * Sets the value of the pointsCurrentWithTwinkHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsCurrentWithTwinkHtml(String value) {
        this.pointsCurrentWithTwinkHtml = value;
    }

    /**
     * Gets the value of the pointsEarnedHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsEarnedHtml() {
        return pointsEarnedHtml;
    }

    /**
     * Sets the value of the pointsEarnedHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsEarnedHtml(String value) {
        this.pointsEarnedHtml = value;
    }

    /**
     * Gets the value of the pointsEarnedWithTwinkHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsEarnedWithTwinkHtml() {
        return pointsEarnedWithTwinkHtml;
    }

    /**
     * Sets the value of the pointsEarnedWithTwinkHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsEarnedWithTwinkHtml(String value) {
        this.pointsEarnedWithTwinkHtml = value;
    }

    /**
     * Gets the value of the pointsSpentHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsSpentHtml() {
        return pointsSpentHtml;
    }

    /**
     * Sets the value of the pointsSpentHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsSpentHtml(String value) {
        this.pointsSpentHtml = value;
    }

    /**
     * Gets the value of the pointsSpentWithTwinkHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsSpentWithTwinkHtml() {
        return pointsSpentWithTwinkHtml;
    }

    /**
     * Sets the value of the pointsSpentWithTwinkHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsSpentWithTwinkHtml(String value) {
        this.pointsSpentWithTwinkHtml = value;
    }

    /**
     * Gets the value of the pointsAdjustmentHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsAdjustmentHtml() {
        return pointsAdjustmentHtml;
    }

    /**
     * Sets the value of the pointsAdjustmentHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsAdjustmentHtml(String value) {
        this.pointsAdjustmentHtml = value;
    }

    /**
     * Gets the value of the pointsAdjustmentWithTwinkHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsAdjustmentWithTwinkHtml() {
        return pointsAdjustmentWithTwinkHtml;
    }

    /**
     * Sets the value of the pointsAdjustmentWithTwinkHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsAdjustmentWithTwinkHtml(String value) {
        this.pointsAdjustmentWithTwinkHtml = value;
    }

}
